theme: jekyll-theme-slate
title: Análisis de tweets de las elecciones generales en EEUU en 2016
description: Proyecto final de la asignatura de Cloud y Big Data del curso 2021/2022. En este proyecto analizaremos tweets referentes a las elecciones de EEUU de 2016. En dicho análisis veremos si la plataforma social representa el pensamiento general de la sociedad.
